### ISSUE TITLE
adding batch is crashing weaviate

### ISSUE THREAD

**Issue by msj121** [weaviate/weaviate#3823]
### How to reproduce this bug?

Simple batch add is no longer working, or rather working in a very limited way (usually crashes, sometimes performs the batch add successfully, maybe 1/10 times):
Weaviate 1.22.5

python:
```
self.client.batch.batch_size = 50
            vectors = self.embedder.embed(batched)
            with self.client.batch as batcher:
                for i,batch in enumerate(batched):
                    uuid = batcher.add_data_object(batch, class_name="TVEpisode",vector=vectors[i])
                    batcher.add_reference(uuid, "TVEpisode", "show", episode["_additional"]["id"], "TVShow")
            gc.collect()
```

### What is the expected behavior?

To add the batched items.

### What is the actual behavior?

Crashes server and restarts

Error response on weaviate server logs:
```
{"action":"request_cacher_dedup_joblist_start","jobs":51,"level":"debug","msg":"starting job list deduplication","time":"2023-11-28T13:43:25Z"}
root-weaviate-1  | {"action":"request_cacher_dedup_joblist_complete","jobs":1,"level":"debug","msg":"completed job list deduplication","removedJobs":50,"time":"2023-11-28T13:43:25Z"}
root-weaviate-1  | {"action":"restapi_request","level":"debug","method":"PATCH","msg":"received HTTP request","time":"2023-11-28T13:43:25Z","url":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/v1/objects/Podcast/f5d30021-1941-4d35-8a8a-4412990f6f86","RawPath":"","OmitHost":false,"ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""}}
root-weaviate-1  | {"action":"restapi_request","level":"debug","method":"POST","msg":"received HTTP request","time":"2023-11-28T13:43:29Z","url":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/v1/graphql","RawPath":"","OmitHost":false,"ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""}}
root-weaviate-1  | {"action":"restapi_request","level":"debug","method":"POST","msg":"received HTTP request","time":"2023-11-28T13:43:31Z","url":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/v1/graphql","RawPath":"","OmitHost":false,"ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""}}
root-weaviate-1  | {"action":"restapi_request","level":"debug","method":"POST","msg":"received HTTP request","time":"2023-11-28T13:43:33Z","url":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/v1/batch/objects","RawPath":"","OmitHost":false,"ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""}}
root-weaviate-1  | {"action":"restapi_request","level":"debug","method":"GET","msg":"received HTTP request","time":"2023-11-28T13:43:34Z","url":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/v1/nodes","RawPath":"","OmitHost":false,"ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""}}
root-weaviate-1  | panic: close of nil channel
root-weaviate-1  | 
root-weaviate-1  | goroutine 109 [running]:
root-weaviate-1  | github.com/weaviate/weaviate/adapters/repos/db.(*vectorQueue).releaseChunk(0xc002822150, 0xc07431de80)
root-weaviate-1  | 	/go/src/github.com/weaviate/weaviate/adapters/repos/db/index_queue.go:732 +0x28
root-weaviate-1  | github.com/weaviate/weaviate/adapters/repos/db.asyncWorker(0x0?, {0x1d38810, 0xc0034cc780}, 0x0?)
root-weaviate-1  | 	/go/src/github.com/weaviate/weaviate/adapters/repos/db/repo.go:366 +0x1b4
root-weaviate-1  | github.com/weaviate/weaviate/adapters/repos/db.New.func1()
root-weaviate-1  | 	/go/src/github.com/weaviate/weaviate/adapters/repos/db/repo.go:169 +0x6b
root-weaviate-1  | created by github.com/weaviate/weaviate/adapters/repos/db.New in goroutine 1
root-weaviate-1  | 	/go/src/github.com/weaviate/weaviate/adapters/repos/db/repo.go:166 +0x76d
root-weaviate-1  | {"action":"startup","level":"debug","msg":"created startup context, nothing done so far","startup_time_left":"59m59.998225659s","time":"2023-11-28T13:43:40Z"}
root-weaviate-1  | {"action":"startup","default_vectorizer_module":"none","level":"info","msg":"the default vectorizer modules is set to \"none\", as a result all new schema classes without an explicit vectorizer setting, will use this vectorizer","time":"2023-11-28T13:43:40Z"}
```

### Supporting information

Class:
```
{
  "class": "TVEpisode",
  "description": "An episode of a TV series",
  "vectorIndexType": "hnsw",
  "invertedIndexConfig": {
    "indexNullState": true,
    "indexPropertyLength": false
  },
  "vectorIndexConfig": {
    "pq": {
      "enabled": true,
      "trainingLimit": 100000,
      "segments": 128
    },
    "skip": false,
    "ef": 64,
    "efConstruction": 128,
    "maxConnections": 32
  },
  "properties": [
    {
      "name": "title",
      "description": "The title of the episode",
      "dataType": ["text"],
      "indexFilterable": true,
      "indexSearchable": true
    },
    {
      "name": "description",
      "description": "A brief summary of the episode",
      "dataType": ["text"],
      "indexFilterable": true,
      "indexSearchable": true
    },
    {
      "name": "tags",
      "description": "Tags for the episode",
      "dataType": ["text[]"],
      "indexFilterable": true,
      "indexSearchable": true
    },
    {
      "name": "duration",
      "description": "The duration of the episode in seconds",
      "dataType": ["int"]
    },
    {
      "name": "position",
      "description": "The position of the episode in the TV series",
      "dataType": ["int"],
      "indexFilterable": false,
      "indexSearchable": false
    },
    {
      "name": "airDate",
      "description": "The date when the episode aired",
      "dataType": ["date"]
    },
    {
      "name": "blocked",
      "description": "This episode is blocked",
      "dataType": ["boolean"],
      "indexFilterable": false,
      "indexSearchable": false
    },
    {
      "name": "seriesId",
      "description": "The series ID that this episode belongs to",
      "dataType": ["uuid"]
    },
    {
      "name": "tvSeries",
      "description": "The TV series that this episode belongs to",
      "dataType": ["TVSeries"]
    },
    {
      "name": "language",
      "description": "The language of the episode",
      "dataType": ["text"]
    },
    {
      "name": "link",
      "description": "A link associated with the episode",
      "dataType": ["text"],
      "indexFilterable": false,
      "indexSearchable": false
    },
    {
      "name": "imageUrl",
      "description": "Image for the episode",
      "dataType": ["text"],
      "indexFilterable": false,
      "indexSearchable": false
    },
    {
      "name": "videoUrl",
      "description": "Link to the video file of the episode",
      "dataType": ["text"],
      "indexFilterable": true,
      "indexSearchable": false
    }
  ]
}
```

There are only 6 million 384d objects on the server, in this collection ~2million and it shouldn't have a problem in terms of space in ram or hd.

### Server Version

1.22.5

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by A-Posthuman** [comment]
I'm also seeing this on 1.22.5, using the quickstart docker file, and "with client.batch as batch:" with the v4 python client.

**Comment by msj121** [comment]
@A-Posthuman I'm also using python client, did you have any success with this? Is just avoiding the batching working for you? I might try that since slow is better then nothing.

**Comment by A-Posthuman** [comment]
I'm just avoiding batches, yes, until this is fixed.

**Comment by msj121** [comment]
Hmm, I can confirm although not perfect does successfully add when done individually and is failing for batch adds.

**Comment by timothepearce** [comment]
I can confirm the bug still exists in `1.23`. @dirkkul, do you have any idea how we can avoid this error from happening?

**Comment by asdine** [comment]
I managed to reproduce it, I'm submitting a fix for v1.23. @msj121 should I submit one for v1.22 as well?

**Comment by timothepearce** [comment]
Thanks @asdine, I’ll try again after the fix is released!

**Comment by art1c0** [comment]
I'm on 1.23.2 and still experience the issue `panic: close of nil channel` when batching

**Comment by dirkkul** [comment]
the fix is not released yet - will be in 1.23.3

**Comment by msj121** [comment]
@asdine Thanks - I can upgrade.
