### ISSUE TITLE
Restoring older backup (pre-1.23.0) does not work 

### ISSUE THREAD

**Issue by jfrancoa** [weaviate/weaviate#4455]
### How to reproduce this bug?

After an incident raised by our SREs in which they couldn't restore a backup obtained when the cluster was in 1.22.5 into a newly created backup in 1.24.0 I decided to dig into the backup_and_restore_version_compatibility pipeline and found out that the issue was also occurring, but it was not caught by the job because the verification logic didn't take into consideration the case in which the query returns an empty list.

To reproduce this issue you can simply checkout the weaviate-chaos-engineering project from branch [backup_restore_fix](https://github.com/weaviate/weaviate-chaos-engineering/tree/backup_restore_fix) and run the job `backup_and_restore_version_compatibility.sh`:
```
WEAVIATE_VERSION="1.23.0" ./backup_and_restore_version_compatibility.sh
```
This will create two nodes, one with 1.15.0 [origin] and another with 1.23.0 [destination], as well as a simulated S3 storage bucket to store the backup. After creating the backup from the origin instance and restoring it in the destination instance, the data check will fail as it will find 0 objects and the query won't return any data.

You can attempt the very same test using a 1.22.X version and see how the test does work fine in that case:
```
WEAVIATE_VERSION="1.22.11" ./backup_and_restore_version_compatibility.sh
```

### What is the expected behavior?

Weaviate can restore backups from a version prior to 1.23.0.

### What is the actual behavior?

Weaviate, after 1.23.0 is able to restore only backups created after 1.23.0, but it is unable to restore backups prior to that version, for example from 1.22.4. The restoration process will succeed but no objects are retrieved, nor the schema. When checking the destination instance, no error logs are observed.

### Supporting information

In case you want more granular testing, you can perform the following steps:

1. Checkout the weaviate-chaos-engineering project from branch [backup_restore_fix](https://github.com/weaviate/weaviate-chaos-engineering/tree/backup_restore_fix)

2. Export the weaviate versions for origin and destination
```
export WEAVIATE_NODE_1_VERSION="1.22.12"
export WEAVIATE_NODE_2_VERSION="1.23.0"
```

3. Clean up the backup directory in case there was data from other run:
```
rm -rf apps/weaviate/backups-s3/
```

4. Startup the containers (weaviate instances and s3)
```
docker-compose -f apps/weaviate/docker-compose-backup.yml up -d weaviate-node-1 weaviate-backup-node backup-s3
```

5. Create the s3 bucket:
```
docker-compose -f apps/weaviate/docker-compose-backup.yml up create-s3-bucket
```

6. Run the test:
```
python3 apps/backup_and_restore_version_compatibility/backup_and_restore_version_compatibility.py
```

### Server Version

1.23.0 (but happens with latest 1.24.1)

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by mikewyer** [comment]
I have seen:

1. 1.22.5 backup restored in a 1.24.1 instance only creating the schema, but not making the data visible.
2. 1.22.5 backup restored in a 1.22.5 instance (yes, the same version) and working correctly, then the data is not visible when the instance is updated to 1.24.1. Downgrade to 1.22.5, data is visible again. Upgrade to 1.24.1 (or 1.23.11) and all the classes are empty again.

**Comment by jfrancoa** [comment]
Fixed in https://github.com/weaviate/weaviate/pull/4457

**Comment by jfrancoa** [comment]
Fixed in https://github.com/weaviate/weaviate/pull/4457

**Comment by I321065** [comment]
> I have seen:
>
> 1. 1.22.5 backup restored in a 1.24.1 instance only creating the schema, but not making the data visible.
> 2. 1.22.5 backup restored in a 1.22.5 instance (yes, the same version) and working correctly, then the data is not visible when the instance is updated to 1.24.1. Downgrade to 1.22.5, data is visible again. Upgrade to 1.24.1 (or 1.23.11) and all the classes are empty again.

Hi,  I want to upgrade 1.22.5 to 1.23.x, such as 1.23.0 、1.23.16 ,  but  all of them has this issue, I also try to another upgrade plan but still failed
1. v1.22.5 -> 1.22.13  good
2. v1.22.5 -> 1.23.0     bad
3. v1.22.13 -> 1.23.16  bad
4. v1.22.5 -> 1.25.x or higher  bad

**Comment by I321065** [comment]
> > I have seen:
> > 
> > 1. 1.22.5 backup restored in a 1.24.1 instance only creating the schema, but not making the data visible.
> > 2. 1.22.5 backup restored in a 1.22.5 instance (yes, the same version) and working correctly, then the data is not visible when the instance is updated to 1.24.1. Downgrade to 1.22.5, data is visible again. Upgrade to 1.24.1 (or 1.23.11) and all the classes are empty again.
> 
> Hi, I want to upgrade 1.22.5 to 1.23.x, such as 1.23.0 、1.23.16 , but all of them has this issue, I also try to another upgrade plan but still failed
> 
> 1. v1.22.5 -> 1.22.13  **success**
> 2. v1.22.5 -> 1.23.0     **fail**
> 3. v1.22.13 -> 1.23.16  **fail**
> 4. v1.22.5 -> 1.25.x or higher  **fail**
> 
> only v1.22.5 -> 1.22.x is success
> 
> @dudanogueira

for this issue I re-export the data and upgrade the version step by step and this issue gone. I guess maybe the data was dirty when I upgrade 1.22 to 1.27 directly, and even though I downgrade the version to 1.22(and the data is available) but it can not be used for other versions
